"""Type stub for xiapl.card (xiapl._xiapl.card): the Card primitive.

Hand-written against the live binding (binding/core_card_utils.cpp,
register_card_module) and verified with mypy.stubtest.
"""

class Card(metaclass=type):
    def __init__(self, rank: int, suit: str) -> None: ...
    @property
    def rank(self) -> int: ...
    @property
    def suit(self) -> str: ...
    @property
    def id(self) -> int: ...
    # Bound with no py::arg (binding/core_card_utils.cpp): the real runtime
    # parameter is positional-only ("arg0").
    @staticmethod
    def from_string(s: str, /) -> Card: ...
    @staticmethod
    def from_id(id: int, /) -> Card: ...
    def to_string(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    # __eq__ is bound with no py::arg (binding/core_card_utils.cpp,
    # register_card_module): the real runtime parameter is positional-only.
    def __eq__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Card, /) -> bool: ...
    def __hash__(self) -> int: ...
