"""Type stub for xiapl.deck (xiapl._xiapl.deck): the Deck primitive.

Hand-written against the live binding (binding/core_deck.cpp,
register_deck_module) and verified with mypy.stubtest.
"""

from collections.abc import Sequence
from typing import overload

from xiapl.card import Card

class Deck(metaclass=type):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, cards: Sequence[Card], /) -> None: ...
    @overload
    def shuffle(self) -> None: ...
    @overload
    def shuffle(self, seed: int) -> None: ...
    def deal(self, n: int = ...) -> list[Card]: ...
    def deal_one(self) -> Card: ...
    def burn(self, n: int = ...) -> None: ...
    # remove_cards/set_cards are bound with no py::arg (binding/core_deck.cpp):
    # the real runtime parameter is positional-only ("arg0"); confirmed
    # remove_cards(cards=[...])/set_cards(cards=[...]) both raise TypeError.
    def remove_cards(self, cards: Sequence[Card], /) -> None: ...
    def reset(self, shuffle: bool = ...) -> None: ...
    def set_cards(self, cards: Sequence[Card], /) -> None: ...
    def size(self) -> int: ...
    def empty(self) -> bool: ...
    def has_cards(self, n: int = ...) -> bool: ...
    @property
    def cards(self) -> list[Card]: ...
    @property
    def card_ids(self) -> list[int]: ...
    def __repr__(self) -> str: ...
