"""Type stub for xiapl.range (xiapl._xiapl.range): range notation parsing.

Hand-written against the live binding (binding/core_range.cpp,
register_range_module) and verified with mypy.stubtest.
"""

from collections.abc import Sequence
from typing import overload

from xiapl.simulation import GameType

class Combo(metaclass=type):
    mask: int
    weight: float
    def __init__(self) -> None: ...

class Range(metaclass=type):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, combos: Sequence[Combo], game: GameType) -> None: ...
    @staticmethod
    def from_string(text: str, game: GameType = ...) -> Range: ...
    @staticmethod
    def all(game: GameType = ...) -> Range: ...
    def combos(self) -> list[Combo]: ...
    def valid_combos(self, dead_mask: int) -> list[Combo]: ...
    def total_weight(self, dead_mask: int = ...) -> float: ...
    def size(self) -> int: ...
    def empty(self) -> bool: ...
    @property
    def game(self) -> GameType: ...
    # Weighted set algebra (max/min lattice): union w = max(wa, wb),
    # intersection w = min(wa, wb), difference w = max(0, wa - wb). Both
    # operands must share the same `game`; a mismatch raises ValueError.
    def union(self, other: Range) -> Range: ...
    def intersection(self, other: Range) -> Range: ...
    def difference(self, other: Range) -> Range: ...
    def __or__(self, other: Range) -> Range: ...
    def __and__(self, other: Range) -> Range: ...
    def __sub__(self, other: Range) -> Range: ...

def try_parse_range(text: str) -> Range | None: ...

# Canonical Hold'em starting-hand labels ("AA", "AKs", "AQo", ...) ranked by
# EXACT equity vs a uniformly random opponent and a uniformly random board,
# strongest first, truncated to floor(169 * top_percent) labels. `game` is
# keyword-only; only GameType.Holdem is ranked in 0.1 (GameType.Plo raises
# ValueError naming the 0.2 roadmap item). top_percent outside (0.0, 1.0]
# raises ValueError.
def rank_starting_hands(
    top_percent: float = ..., *, game: GameType = ...
) -> list[str]: ...

# The same selection as a Range at weight 1.0 (every combo of every kept
# label). Equivalent to
# Range.from_string(",".join(rank_starting_hands(top_percent)), game=game).
def generate_top_percent_range(
    top_percent: float, *, game: GameType = ...
) -> Range: ...
