"""Type stub for xiapl.simulation (xiapl._xiapl.simulation): equity simulation +
GameType (the enum shared by xiapl.eval and xiapl.range; see
binding/core_simulation.cpp's register_simulation_gametype for why it lives
here).

Hand-written against the live binding (binding/core_simulation.cpp) and
verified with mypy.stubtest.
"""

from collections.abc import Sequence
from typing import Any

from xiapl.range import Range

class GameType(metaclass=type):
    Holdem: GameType
    Plo: GameType
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    __members__: dict[str, GameType]

class SimulationMode(metaclass=type):
    Exact: SimulationMode
    MonteCarloRandom: SimulationMode
    MonteCarloSeeded: SimulationMode
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    __members__: dict[str, SimulationMode]

class SimulationOptions(metaclass=type):
    iterations: int
    seed: int
    deterministic: bool
    threads: int
    def __init__(self) -> None: ...
    def effective_mode(self) -> SimulationMode: ...
    @staticmethod
    def exact() -> SimulationOptions: ...
    @staticmethod
    def mc_random(iterations: int) -> SimulationOptions: ...
    @staticmethod
    def mc_seeded(iterations: int, seed: int) -> SimulationOptions: ...

class PlayerEquity(metaclass=type):
    # No py::init bound: instances are only produced by calculate_equity.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def winrate(self) -> float: ...
    @property
    def equity(self) -> float: ...
    @property
    def std_error(self) -> float: ...

class EquityResult(metaclass=type):
    # No py::init bound: instances are only produced by calculate_equity.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def players(self) -> list[PlayerEquity]: ...
    @property
    def chop_rate(self) -> float: ...
    @property
    def trials(self) -> int: ...
    @property
    def exact(self) -> bool: ...

class RangeEquityMode(metaclass=type):
    PerCombo: RangeEquityMode
    AggregateOnly: RangeEquityMode
    PER_COMBO: RangeEquityMode  # deprecated alias
    AGGREGATE_ONLY: RangeEquityMode  # deprecated alias
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    __members__: dict[str, RangeEquityMode]

class RangeEquityEntry(metaclass=type):
    # No py::init bound: instances are only produced by calculate_range_equity.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def combo_mask(self) -> int: ...
    @property
    def equity(self) -> float: ...
    @property
    def weight(self) -> float: ...

class RangeEquityResult(metaclass=type):
    # No py::init bound: instances are only produced by calculate_range_equity.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def hero(self) -> list[RangeEquityEntry]: ...
    @property
    def villain(self) -> list[RangeEquityEntry]: ...
    @property
    def hero_aggregate_equity(self) -> float: ...
    @property
    def villain_aggregate_equity(self) -> float: ...
    @property
    def trials(self) -> int: ...
    @property
    def exact(self) -> bool: ...
    @property
    def aggregate_std_error(self) -> float: ...

# Both entry points release the GIL for the duration of the C++ call via a
# py::gil_scoped_release scoped INSIDE the lambda body (binding/core_simulation.cpp,
# not a py::call_guard<gil_scoped_release> -- see the comment there for why);
# no effect on the Python-visible type signature either way.
def calculate_equity(
    hole_masks: Sequence[int],
    board_mask: int,
    options: SimulationOptions,
    *,
    game: GameType = ...,
) -> EquityResult: ...

# `mode` is positional-or-keyword at the binding site (no py::kw_only()
# marker precedes it, unlike `game` above) -- transcribed as such.
def calculate_range_equity(
    hero_range: Range,
    villain_range: Range,
    board_mask: int,
    options: SimulationOptions,
    mode: RangeEquityMode = ...,
) -> RangeEquityResult: ...
